### PR TITLE
Created about us page, login pages  and registration pages.

### LINKED ISSUE #7: Code registration, login and about us page
design user registration page, user and admin login page and about us page

### PR DESCRIPTION
**Pull request by ebukaharry**
closes #7

### CODE REVIEW

**Comment by ebukaharry** [comment]
resolves #7

**Comment by seunbayo** [comment]
Make pr to develop not main

**Comment by seunbayo** [comment]
conflicting files, resolve conflicts

**Comment by seunbayo** [comment]
Resolve conflicts

**Pull request merged**
